### ISSUE TITLE
M3 - New ActivityPub Client

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#102]
Launch date: May 10th

Develop a new ActivityPub client which will support natively loading published data over p2p protocols, skipping the need for always-online HTTP servers for accessing content. 

- [x] New project `reader.distributed.press`
- [x] Render ActivityPub posts in UI by loading them on the fly (1 week) @akhileshthite 
  - [x] Support loading from p2p URLs (native or via gateways)
  - [x] UI to configure gateway
- [x] Read from users outboxes into a feed (0.5 week)
  - [x] Read staticpub inbox to start, have interface that takes a "num posts" and "page" param and has an async iterator of Activities.
  - [x] Handle create/update/
- [x] Ingest posts/outbox into local Database (leveljs over indexeddb)
  - [ ] RDF traversal library that works over `fetch` and resolves links as we traverse (1 week)
  - [ ] Basic API for handling AP traversal
  - [x] Index Notes from activities in addition to activities themselves (1 week)
  - [x] Track update times
- [x] Track followed accounts and have a button to download updates (1 week)
   - [x] Have a page to track them
   - [x] Save their IDs in local storage
   - [x] Code to traverse their outboxes and ingest them into the db
- [x] Render "timeline" of posts (maybe we can experiment here) (2 weeks)

**Comment by RangerMauve** [comment]
- New project `reader.distributed.press`
- Low javascript, no framework, multi page application using web components, no server component (little or no) build system.
- Render ActivityPub posts in UI by loading them on the fly
- Support loading from p2p URLs (native or via gateways)
- UI to configure gateway
- Read from users outboxes into a feed
- Ingest posts/outbox into local Database (leveljs over indexeddb)
- Render "timeline" of posts (maybe we can experiment here)

Nice to have: Different filter options for timeline (using querystrings and being able to save views)
Nice to have: Basic color scheme customization to make it feel like "their own"

**Comment by RangerMauve** [comment]
Load this as a post: hyper://staticpub.mauve.moe/helloworld.html

- [ ]  Fetch from IPFS
- [ ] Detect that it's html and get the `link[rel=alternate]` tag to get the json-ld URL
- [ ] Resolve the json-ld object and render it's content

**Comment by RangerMauve** [comment]
Use https://developer.mozilla.org/en-US/docs/Web/API/DOMParser for parsing the html, then `querySelector` to get the link

**Comment by RangerMauve** [comment]
Assume that the IPFS URLs of all the objects will be the same domain but with `ipfs://`

Test it in Agregore or Peersky or Brave to try direct IPFS loading

**Comment by akhileshthite** [comment]
reader thread UI ideas:
https://trunks.social/status/mastodon.social/@ErickaSimone/112006693608642877

recursive/nested `<blockquote>`

**Comment by sutty-coop** [comment]
Launch date: March 27th?

**Comment by akhileshthite** [comment]
> Launch date: March 27th?

29th, Friday?

**Comment by RangerMauve** [comment]
This is about to get launched
