### ISSUE TITLE
Reader database index

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#118]
Ingest posts/outbox into local Database (leveljs over indexeddb)
 - RDF traversal library that works over fetch and resolves links as we traverse (1 week)
 - Basic API for handling AP traversal
 - Index Notes from activities in addition to activities themselves (1 week)
 - Track update times

Chech the boxes in https://github.com/hyphacoop/distributed-press-organizing/issues/102 when it's done :)

**Comment by RangerMauve** [comment]
- get js file for idb https://www.npmjs.com/package/idb
- create a new db for storing data
- start adding objects from outboxes into it
- index by time and by autho
- search by time and by author
- add from our inbox (eventually)
