### ISSUE TITLE
Finish Announcement backend and routes

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#123]
Check the corresponding boxes in #101 when this is done

**Comment by fauno** [comment]
@RangerMauve is this been worked on by @catdevnull too?

**Comment by RangerMauve** [comment]
Yes

**Comment by RangerMauve** [comment]
TODO for tomorrow:

fix the tests
clean up the code and add docs
filter out notes when getting the outbox list
have 
[Akhilesh Thite](https://matrix.to/#/@akhilesh.thite:matrix.org)
 test loading the outbox in the reader
prep for prod

**Comment by RangerMauve** [comment]
Have announcements set up an allowlist to `@*@*` to auto approve followers (or have an autoApprove flag?)
