### ISSUE TITLE
M4 Replies in Social Inbox

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#127]
- [ ] check if this issue covers the tasks: https://github.com/hyphacoop/distributed-press-organizing/issues/96
 
- [ ] provide api for getting replies

- [ ]  filter by post being replied to or root post

- [ ] have the staticpub demo and jekyll plugin link to replies url or pull them as static files

**Comment by RangerMauve** [comment]
This is done, just doing some bug fixing and testing
