### ISSUE TITLE
M4 HTML snippet "Published with dP"

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#131]
- [ ] snippets for templates
- [ ] link to reader to follow the blog
- [ ] link to dp explainer?

**Comment by fauno** [comment]
When we talked about this I imagined a button that opens a webpage where you could see all protocols enabled, their addresses and possibly documentation on how to access them.

**Comment by fauno** [comment]
https://anlucas.neocities.org/88x31Buttons :D

**Comment by fauno** [comment]
@AnaFukelman we need to check this with uxdi

**Comment by AnaFukelman** [comment]
@akhileshthite when you have completed the pending tasks in this deliverable, would you let me know if you have included each of this three items or any of this is discarded? 👇 so we report accurately to FFDW
- Develop snippets for templates 
- Link to reader to follow the blog 
- Potentially link to Distributed Press explainer

**Comment by akhileshthite** [comment]
@RangerMauve where should we add this? In docs?
Also our main site's footer/blogs?

**Comment by RangerMauve** [comment]
In the docs and in the template

**Comment by RangerMauve** [comment]
https://github.com/hyphacoop/docs.distributed.press/pull/23

In docs

**Comment by RangerMauve** [comment]
Added to template for SDK

**Comment by RangerMauve** [comment]
Merged into docs
