### ISSUE TITLE
M4 Reported accounts

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#136]
We need to talk more about what the UX is - we want admins to detect if there's a report received in the Social Inbox
Fauno & Mauve will adress this in terms of funciontality.
Then we can ask for UXDI team's POV
Work on the Social inbox and work on the Sutty panel

**Comment by RangerMauve** [comment]
currently seeing flagged posts in the sutty console. We can get notifications on new flags.

**Comment by RangerMauve** [comment]
Should have UX for what happens when a site needs to be deleted. MArk it as deleted i8n the CMS? What are the admin tools we can make on the social inbox side for it?

**Comment by fauno** [comment]
Sutty CMS:

* Get notification when a site is flagged
* Notifies the Social Inbox of blocked accounts

Social Inbox:

* Admins can disable accounts
* Admins can blocklist local accounts

**Comment by RangerMauve** [comment]
Could have sutty CMS notify the inbox on bad accounts and hypha can have a flow for dealing with them

**Comment by RangerMauve** [comment]
Need to send Delete events to all instances when an account is killed.

**Comment by RangerMauve** [comment]
Add tombstone account instead of just deleting?

**Comment by fauno** [comment]
Will draft up the process with the UXDI team starting next week

**Comment by fauno** [comment]
Follow up on changes on the CMS is over here:

https://0xacab.org/sutty/sutty/-/issues/17549

**Comment by fauno** [comment]
@RangerMauve I'll need the endpoint and request type to send this, I imagine something like this, can you confirm?

```
# Sends Delete(Actor) activities to the interacted collection.
# 
# It can be used by Actors to remove themselves from the Fediverse.
DELETE /v1/:actor/inbox/delete

# Add the actor to the local blocklist, send out Delete(Actor)  to interacted, replace inbox with Tombstone, etc.
POST /v1/:actor/flag
```

**Comment by fauno** [comment]
> Follow up on changes on the CMS is over here:
> 
> https://0xacab.org/sutty/sutty/-/issues/17549

Translation: Moderators (Sutty Coop for now) will receive an email notification and they can block the site by replacing the whole site with 410 Gone pages and send out a call to the Social Inbox.  Possibly a Tombstone for any .jsonld file or at least for the Actor. Also blocking a user will do the same for every site they have and prevent login.

**Comment by RangerMauve** [comment]
TODO:
- [ ] Add delete for inbox
- [ ] Track reports for admins (admin level webhooks)

**Comment by fauno** [comment]
Related https://github.com/hyphacoop/social.distributed.press/issues/88

**Comment by RangerMauve** [comment]
We already have an API for deleting actors 😅 `DELETE /v1/:actor`. This will delete the inbox/outbox/etc

**Comment by AnaFukelman** [comment]
@fauno hi! could you report on the progress of this? I remember us reporting this as a deliverable of M4

**Comment by RangerMauve** [comment]
I think this has been integrated into the Sutty CMS

**Comment by RangerMauve** [comment]
Confirmed
