### ISSUE TITLE
Auto-follow when manuallyApprovesFollowers is present and false

### ISSUE THREAD

**Issue by fauno** [hyphacoop/distributed-press-organizing#153]
An Actor with manuallyApprovesFollowers set to false should auto-accept Follow requests and dispatch an onapproved webhook. With this a website can control if they want to handle follows themselves or let the Social Inbox do that for them.

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers"
    }
  ],
  "type": "Person",
  "manuallyApprovesFollowers": true,
}

```

**Comment by fauno** [comment]
Note `APActor` type doesn't include this attribute.

**Comment by fauno** [comment]
Something @catdevnull could implement early on M4

**Comment by catdevnull** [comment]
should this be available for all actors or just used in the announcements actor?

**Comment by RangerMauve** [comment]
All actors would be best IMO

**Comment by RangerMauve** [comment]
Hmm, maybe we can start with setting this flag in the setInfo call to start? Just worried we'd have cache invalidation issues and extra requests otherwise.

**Comment by fauno** [comment]
I meant for all actors yeah. @RangerMauve the Jekyll plugin sends an Update for the Actor object when it detects it changed, so we should be fine (we did this so profile pics and info was correctly updated)

**Comment by catdevnull** [comment]
isn't this (seemingly incorrectly) implemented by https://github.com/hyphacoop/social.distributed.press/commit/2f97d573a170a5e8e40bec786dbafdad1f819a2e?

**Comment by sutty-coop** [comment]
Asignade a Agus - necesitamos su usuarie de Github

**Comment by RangerMauve** [comment]
Technically we have an alternative for this already in the account info when you create your account, but it might be useful to also pull this setting from the actor to simplify deployment further.

**Comment by RangerMauve** [comment]
I think we should add some sort of caching to our http requests first.

**Comment by fauno** [comment]
> Technically we have an alternative for this already in the account info when you create your account, but it might be useful to also pull this setting from the actor to simplify deployment further.

Doesn't this line implement it?

https://github.com/hyphacoop/social.distributed.press/blob/main/src/server/apsystem.ts#L355

**Comment by RangerMauve** [comment]
Could you elaborate on your point? The line you linked to is empty for me.

**Comment by RangerMauve** [comment]
The functionality fetches from the info stored in the local store, not from the actor published on AP.

**Comment by fauno** [comment]
> The functionality fetches from the info stored in the local store, not from the actor published on AP.

oooh i see!

**Comment by sutty-coop** [comment]
@fauno does this conversation above ☝ mean that @magush27 has to fix their code to fetch info from the actor instead of the local storage? If affirmative, let's ask Agus if they need any help changing this

**Comment by fauno** [comment]
No need! Just moved it to another part of the plugin and now it works!
