### ISSUE TITLE
After first follow from an instance, resend activities

### ISSUE THREAD

**Issue by fauno** [hyphacoop/distributed-press-organizing#156]
We talked about this a few times but couldn't find an issue reported.

Related to https://github.com/hyphacoop/distributed-press-organizing/issues/101

When you look for an Actor profile on Mastodon, and the Actor doesn't have any previous followers from your instance, Mastodon will fetch the Actor to show a profile, but won't fetch activities. So it shows an empty profile with a tiny message saying you need to go visit the remote profile if you want to read previous activities.

This has been surprising to people testing Sutty + Social Inbox.

But if the Social Inbox resends some activities when a new instance is detected, we can prevent confusing all users from that instance.  Only the first one :P

@rangermauve mentioned they're tracking an issue on Mastodon that could solve this entirely, could you link it here?

**Comment by RangerMauve** [comment]
This is the main tracking issue on the mastodon side https://github.com/mastodon/mastodon/issues/34

**Comment by fauno** [comment]
New instance detection means first follower from an unknown instance.

**Comment by sutty-coop** [comment]
We move this goal from M3 to M4

**Comment by fauno** [comment]
We need to test if Mastodon will take old activities first

**Comment by RangerMauve** [comment]
https://github.com/mastodon/mastodon/issues/34

**Comment by RangerMauve** [comment]
Closed by https://github.com/hyphacoop/social.distributed.press/pull/87
