### ISSUE TITLE
Followers should return an empty collection for unathenticated requests

### ISSUE THREAD

**Issue by fauno** [hyphacoop/distributed-press-organizing#157]
I'm checking what Mastodon does with the followers collection for unauthenticated requests and I find it responds with an empty OrderedCollection with totalItems equal the number of current followers.  I'm guessing this allows Mastodon to show a followers count on the profile without exposing them individually.

**Comment by RangerMauve** [comment]
Good idea!

**Comment by fauno** [comment]
Details: https://github.com/hyphacoop/social.distributed.press/issues/28#issuecomment-2077924155
