### ISSUE TITLE
Ensure activities are deleted when requested

### ISSUE THREAD

**Issue by fauno** [hyphacoop/distributed-press-organizing#159]
We were talking with a client and the first thing they asked is if they would be able to remove activities after publication.

So far we are sending Delete activities when a post is removed, and the Social Inbox has been relaying them to followers, but what happens when an actor stops following?  Shouldn't the Social Inbox send Delete activities to the instances too?

Also how are Delete activities distributed across non-following instances?  For instance, if I don't follow a site hosted by the Social Inbox, but I read a thread and my instance completes the thread by fetching the activity from the site.

**Comment by fauno** [comment]
Same for Actors, how can we remove them?

**Comment by gobengo** [comment]
I think you can't guarantee to the client that everything will be deleted everywhere even on remote instances. All you can do is delete on your end, consider serving a tombstone that the thing was deleted on your end, and a 'best effort' of sending Deletes.

> what happens when an actor stops following?

up to you

> Shouldn't the Social Inbox send Delete activities to the instances too?

sure, that sounds like a nice thing to do. I don't think you're required to send things to non-followers though.

> Also how are Delete activities distributed across non-following instances?

generally activitypub doesn't define how to distribute across non-following instances I think

> Same for Actors, how can we remove them?

I don't think you can remove them from remote instances, but you can always send a Delete activity wherever you want, you just can't force the receiver to process it any sort of way esp if they aren't following you. But for any object whose id is a URL you control, you can serve whatever you want incl a 404.

**Comment by fauno** [comment]
Thanks @gobengo!

@RangerMauve is it possible for the Social Inbox to relay Delete activities to all instances previously following their Actor?  The idea would be to ask instances to remove cached activities even if they're not being notified of new activities, because they don't follow the Actor anymore, but potentially got notified of older activities.

**Comment by RangerMauve** [comment]
We should track not just followers, but all folks you interacted with
This can be at a new route beside `/v1/:account/followers` like `/v1/:account/interactions`.

then when doing a delete (or anything else) we can cc this collection and send it to all those instances.

**Comment by fauno** [comment]
We talked it could be an append-only collection of shared inboxes  hyphacoop/social.distributed.press#32 so we can address all known instances

**Comment by fauno** [comment]
I'm thinking maybe we scope it as a FEP?

**Comment by RangerMauve** [comment]
**see https://github.com/hyphacoop/social.distributed.press/pull/84#issue-2433518704**

- [ ] Add a new AccountListStore to the ActorStore under "interacted"
- [ ] In the inbox, track replies/followers and add them to the interacted store
- [ ] Add new endpoint under `/v1/:actor/interacted` which returns the list of interacted peers
- [ ] In the outbox detect when the interacted store is CC'd in the activity, and send the activity to all listed users instead of the followers list
- [ ] Add endpoint to client API
- [ ] Add unit tests for the HTTP API
- [ ]  Update Jekyll plugin with a delete command which uses this new field
- [ ] Final testing

**Comment by fauno** [comment]
We agreed today to push this to next milestone!

**Comment by sutty-coop** [comment]
We have to find someone who can do this issue, if Nula cannot work on it now @sutty-coop
