### ISSUE TITLE
Auto-accept remote Deletes

### ISSUE THREAD

**Issue by fauno** [hyphacoop/distributed-press-organizing#162]
On distributed-press-api-client I hardcoded a 1MiB limit to responses to prevent being zip bombed and today the response for `@sutty@sutty.nl` inbox was failing because it contains 4608 Delete activities xD

I think SI should:

* Auto-accept remote Deletes
* Send an onapprove hook so the CMS can delete locally

Related hyphacoop/distributed-press-organizing#159 hyphacoop/distributed-press-organizing#163

**Comment by fauno** [comment]
Note: The 1MiB hard-limit came from Mastodon

**Comment by sutty-coop** [comment]
@fauno debería pasarle la información a Agus para que pueda abordar este issue

**Comment by sutty-coop** [comment]
I checked with Agus on July 11th and they said this is pending. I'll update estimated completion date by end of July.

CHANGES: Mauve mentions that we ignore deletes related to Actors we've been before. This helps avoid SPAM from Mastodon

TO-DO:
- [ ] respect the delete to remove notes from deleted users and for deleted activities

**Comment by fauno** [comment]
The Social Inbox is currently:

* Ignoring Deletes if the account is not on the interacted collection, so we don't have to deal with deletion of unknown actors.
* Sending Deletes to Sutty's hooks for moderation. Sutty is emptying the object locally (it should change them to Tombstones) but doesn't notify the Inbox about this as an approval.

The implementation should:

* Process incoming Deletes immediately by:
  * Removing the activity from the inbox and any other index/collection
    * (Not sure if removing an activity from the inbox would remove it from other indexes)
  * Dispatch an onapproved hook, so the CMS can still remove the object locally

**Comment by AnaFukelman** [comment]
@magush27 and @fauno tenemos una fecha estimada de cierre de este issue?

**Comment by magush27** [comment]
> @magush27 and @fauno tenemos una fecha estimada de cierre de este issue?

si! ya casi está, ahi le escribo a fauno porque necesitaba una mano para subirlo nada más

**Comment by RangerMauve** [comment]
This is done! Will release soon
