### ISSUE TITLE
Fetching Followers collection fails when a remote instance is down

### ISSUE THREAD

**Issue by fauno** [hyphacoop/distributed-press-organizing#169]
🎯 **Success criteria:** don't fail :P

## Task Summary

![image](https://github.com/hyphacoop/distributed-press-organizing/assets/468204/ca3e87dc-af90-4de9-8b01-c3dc63a5dcea)

Fetching the Follower list for distributed.press fails because an instance is down. Apparently it's trying to solve Webfinger for followers.

Related to:

* https://github.com/hyphacoop/social.distributed.press/issues/55 
* https://github.com/hyphacoop/distributed-press-organizing/issues/154

**Comment by RangerMauve** [comment]
Yeah we should detect failed accounts and delete them

**Comment by fauno** [comment]
> Yeah we should detect failed accounts and delete them

This is a temporarily out of order instance, so skipping then would be best. But my question is why do we need to issue requests to remote servers for locally available data?

**Comment by RangerMauve** [comment]
The data isn't cached locally yet. :sweat_smile: At least not actors outside our instance.

**Comment by RangerMauve** [comment]
Oh, the specific issue is we store the follower in the mention format instead of the actor URL so we need to convert on list.

**Comment by fauno** [comment]
> Oh, the specific issue is we store the follower in the mention format instead of the actor URL so we need to convert on list.

Is it difficult to store the different formats for actor addressing locally? Do they change in practice?

**Comment by RangerMauve** [comment]
We could do a database migration to link to actors instead of webfinger, yeah. It's not a trivial amount of work since we'd need to do a DB migration. We'd need to rework a bunch of validation logic too.

**Comment by fauno** [comment]
can't we have a map stored separately though?

**Comment by RangerMauve** [comment]
Like a cache of webfinger to actor? That could be done, yes. Honestly we probably should have made the webfinger part optional and just resolved it to the actor url past the http route. :sweat_smile:

**Comment by sutty-coop** [comment]
This will be better once we have proper cache
