### ISSUE TITLE
Small issue with bullets in the Fedi version

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#173]
Every time we use bullets in an article, they appear with a few blank spaces in the Fedi account.
I'm using Google Chrome version 125.0.6422.76

![Image](https://github.com/hyphacoop/distributed-press-organizing/assets/113475467/320d7f8e-d21a-412a-b117-046f0d154e59)

**Comment by fauno** [comment]
@catdevnull i was going to say this is because our html editor adds paragraphs inside list items, but apparently it's the whitespace between them, that's different between the css on the site than on mastodon. i have just the issue opened for this.

**Comment by fauno** [comment]
apparently mastodon adds it's own whitespace, because i removed it from the source and it still shows the same. or there's caching involved. i'll debug further.

**Comment by fauno** [comment]
@tripledoublev i fixed it on 0.2.10, just upgrade if you're experiencing white space issues on hypha.coop

**Comment by fauno** [comment]
@RangerMauve i fixed it but i don't have permission to push to https://github.com/hyphacoop/distributed.press

**Comment by RangerMauve** [comment]
@fauno added you to distributed.press

**Comment by fauno** [comment]
@RangerMauve could you add @sutty-coop too? so the cms can push changes too

**Comment by RangerMauve** [comment]
@fauno sutty-coop is already added to the distributed.press repo

**Comment by RangerMauve** [comment]
Can this be closed?

**Comment by fauno** [comment]
I see correct spacing when I look at activities for @dripline@hypha.coop
