### ISSUE TITLE
Replies can't be found on the replies collection after being approved

### ISSUE THREAD

**Issue by fauno** [hyphacoop/distributed-press-organizing#179]
This article: https://sutty.nl/primer-encuentro-del-nodo-dweb-sudaka/

Has an activity: https://sutty.nl/primer-encuentro-del-nodo-dweb-sudaka.jsonld

If you look for it on a Mastodon instance, you may find it has three replies. The one from June 14th was done to test the replies collection. The reply got into the moderation queue and was approved.

The ID of the approved activity is https://todon.nl/users/f/statuses/112615887762448334/activity and I can find it on the inbox (after digging through the 36k delete activities). If I accept it again, I get an "ok" from social.distributed.press.

This is what I'm running manually on Sutty's console:

```ruby
site = Site.find_by_name "sutty.nl."
site.social_inbox.inbox.accept(id: "https://todon.nl/users/f/statuses/112615887762448334/activity")
```

But the counter at https://social.distributed.press/v1/@sutty@sutty.nl/inbox/replies/https%3A%2F%2Fsutty.nl%2Fprimer-encuentro-del-nodo-dweb-sudaka.jsonld remains at zero.

**Comment by fauno** [comment]
By looking at ActivityPubSystem's approveActivity I don't see where the reply gets indexed :thinking:

**Comment by fauno** [comment]
@sutty-coop can you add it to the milestone?

**Comment by akhileshthite** [comment]
> This article: https://sutty.nl/primer-encuentro-del-nodo-dweb-sudaka/
> 
> Has an activity: https://sutty.nl/primer-encuentro-del-nodo-dweb-sudaka.jsonld
> 
> If you look for it on a Mastodon instance, you may find it has three replies. The one from June 14th was done to test the replies collection. The reply got into the moderation queue and was approved.
> 
> The ID of the approved activity is https://todon.nl/users/f/statuses/112615887762448334/activity and I can find it on the inbox (after digging through the 36k delete activities). If I accept it again, I get an "ok" from social.distributed.press.
> 
> This is what I'm running manually on Sutty's console:
> 
> ```ruby
> site = Site.find_by_name "sutty.nl."
> site.social_inbox.inbox.accept(id: "https://todon.nl/users/f/statuses/112615887762448334/activity")
> ```
> 
> But the counter at https://social.distributed.press/v1/@sutty@sutty.nl/inbox/replies/https%3A%2F%2Fsutty.nl%2Fprimer-encuentro-del-nodo-dweb-sudaka.jsonld remains at zero.

For that article, instead of 1 it's showing 0 items:
https://social.distributed.press/v1/@sutty@sutty.nl/inbox/replies/https%3A%2F%2Fsutty.nl%2Fprimer-encuentro-del-nodo-dweb-sudaka.jsonld

Here's an example of a sutty post with no replies:
https://social.distributed.press/v1/@sutty@sutty.nl/inbox/replies/https%3A%2F%2Fsutty.nl%2Flanzamiento-nueva-funci%25C3%25B3n-de-moderaci%25C3%25B3n-para-los-sitios-conectados-al-fediverso.jsonld

```
{"message":"Route GET:/v1/@sutty@sutty.nl/inbox/replies/https%3A%2F%2Fsutty.nl%2Flanzamiento-nueva-funci%25C3%25B3n-de-moderaci%25C3%25B3n-para-los-sitios-conectados-al-fediverso.jsonld not found","error":"Not Found","statusCode":404}
```

It gives 404 "not found", hence not able to fetch. It should be 0 items, correct?

**Comment by fauno** [comment]
> Here's an example of a sutty post with no replies: https://social.distributed.press/v1/@sutty@sutty.nl/inbox/replies/https%3A%2F%2Fsutty.nl%2Flanzamiento-nueva-funci%25C3%25B3n-de-moderaci%25C3%25B3n-para-los-sitios-conectados-al-fediverso.jsonld
> 
> ```
> {"message":"Route GET:/v1/@sutty@sutty.nl/inbox/replies/https%3A%2F%2Fsutty.nl%2Flanzamiento-nueva-funci%25C3%25B3n-de-moderaci%25C3%25B3n-para-los-sitios-conectados-al-fediverso.jsonld not found","error":"Not Found","statusCode":404}
> ```
> 
> It gives 404 "not found", hence not able to fetch. It should be 0 items, correct?

Nope, this is related to hyphacoop/social.distributed.press#67 because the replies collection is not checking that the ID actually exists, for instance I can get an empty collection for IDs that were never activities, so the 404 is unrelated to this issue.

**Comment by fauno** [comment]
Here's the full activity with inReplyTo field @RangerMauve 

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "ostatus": "http://ostatus.org#",
      "atomUri": "ostatus:atomUri",
      "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
      "conversation": "ostatus:conversation",
      "sensitive": "as:sensitive",
      "toot": "http://joinmastodon.org/ns#",
      "votersCount": "toot:votersCount"
    }
  ],
  "id": "https://todon.nl/users/f/statuses/112615887762448334/activity",
  "type": "Create",
  "actor": "https://todon.nl/users/f",
  "published": "2024-06-14T16:21:16Z",
  "to": [
    "https://todon.nl/users/f/followers"
  ],
  "cc": [
    "https://www.w3.org/ns/activitystreams#Public",
    "https://sutty.nl/about.jsonld"
  ],
  "object": {
    "id": "https://todon.nl/users/f/statuses/112615887762448334",
    "type": "Note",
    "summary": "Primer Encuentro del Nodo dWeb Sudaka",
    "inReplyTo": "https://sutty.nl/primer-encuentro-del-nodo-dweb-sudaka.jsonld",
    "published": "2024-06-14T16:21:16Z",
    "url": "https://todon.nl/@f/112615887762448334",
    "attributedTo": "https://todon.nl/users/f",
    "to": [
      "https://todon.nl/users/f/followers"
    ],
    "cc": [
      "https://www.w3.org/ns/activitystreams#Public",
      "https://sutty.nl/about.jsonld"
    ],
    "sensitive": true,
    "atomUri": "https://todon.nl/users/f/statuses/112615887762448334",
    "inReplyToAtomUri": "https://sutty.nl/primer-encuentro-del-nodo-dweb-sudaka.jsonld",
    "conversation": "tag:todon.nl,2024-04-15:objectId=121346076:objectType=Conversation",
    "content": "<p><span class=\"h-card\" translate=\"no\"><a href=\"https://sutty.nl\" class=\"u-url mention\">@<span>sutty</span></a></span> pronto sale el segundo :O</p>",
    "contentMap": {
      "es": "<p><span class=\"h-card\" translate=\"no\"><a href=\"https://sutty.nl\" class=\"u-url mention\">@<span>sutty</span></a></span> pronto sale el segundo :O</p>"
    },
    "attachment": [],
    "tag": [
      {
        "type": "Mention",
        "href": "https://sutty.nl/about.jsonld",
        "name": "@sutty@sutty.nl"
      }
    ],
    "replies": {
      "id": "https://todon.nl/users/f/statuses/112615887762448334/replies",
      "type": "Collection",
      "first": {
        "type": "CollectionPage",
        "next": "https://todon.nl/users/f/statuses/112615887762448334/replies?only_other_accounts=true&page=true",
        "partOf": "https://todon.nl/users/f/statuses/112615887762448334/replies",
        "items": []
      }
    }
  }
}
```

**Comment by RangerMauve** [comment]
Is the activity visible inside the sutty.nl inbox?

**Comment by RangerMauve** [comment]
Also was that reply approved or auto-approved?

**Comment by fauno** [comment]
> Also was that reply approved or auto-approved?

approved

> Is the activity visible inside the sutty.nl inbox?

the reply? yeah, it's there and i approved it manually via the ruby repl just in case

**Comment by RangerMauve** [comment]
I did a bunch of fixes and it seems replies are working now.

https://social.dp.chanterelle.xyz/v1/@mauve@staticpub.mauve.moe/inbox/replies/https%3A%2F%2Fstaticpub.mauve.moe%2Fnewpost.jsonld

I'll get a PR in and hopefully we can release the fix tomorrow.

**Comment by RangerMauve** [comment]
Not sure if my social inboxes changes fixed anything or whether there's some other issue. Lets try doing another reply once we publish the changes.

**Comment by RangerMauve** [comment]
I found the issue!  the inbox is currently not checking the cc field
