### ISSUE TITLE
September social media posts

### ISSUE THREAD

**Issue by AnaFukelman** [hyphacoop/distributed-press-organizing#192]
Posts:
https://hackmd.io/@afukelman/SyfWbfv6R

**Comment by anawingu** [comment]
https://x.com/dwebpress/status/1831354280651190731

https://x.com/dwebpress/status/1838958687173394887

https://social.coop/@distributedpress/113198875558383597

**Comment by AnaFukelman** [comment]
https://x.com/dwebpress/status/1831354280651190731

https://x.com/dwebpress/status/1838958687173394887

https://social.coop/@distributedpress/113198875558383597
