### ISSUE TITLE
Have a cli for talking to dp/ api social inbox

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#194]
- [ ] Expose all HTTP endpoints
- [ ] Pass in keypair / auth token using https://www.npmjs.com/package/rc
- [ ] Show example of creating a new site on DP, registering it with social inbox, and sending a post to followers

**Comment by AnaFukelman** [comment]
Hi! I wanted to check if you corrected the approach here, via Mauve's suggestion of how to trigger the clone instead of scrapping the site. Let me know the status of this and if/when we can close this issue as Done @akhileshthite

**Comment by RangerMauve** [comment]
Just need to wrap some final polishing on the clone command

**Comment by RangerMauve** [comment]
Done!
