### ISSUE TITLE
Create texts for each section

### ISSUE THREAD

**Issue by AnaFukelman** [hyphacoop/distributed-press-organizing#196]
Some texts have yet to be written

- FAQs https://hackmd.io/su4hIe3iTDqi0Oarc7y-zA?view
- Pricing section (For now it is free for [X conditions] but [let's talk]. his is here because people will ask, so even it is free for now, it should be shown clearly (no hidden limits) to the best of our current knowledge.) -- this will also be shown in the "Get a token" section
- Instructions for the "cloning" 1st screen
  - Enter the domain name of the site you wish to clone
  - You must have control over the DNS records for your site
  - Open your your DNS provier panel
  - Add a new NAMESPACE record for `_dnslink.{your domain` pointing to `api.distributed.press`
  - When ready click "check DNS" to see if resolving worked
  - Once DNS resolving is successful click CLONE
  - Wait for cloning to happen
  - View the site via a gateway

**Comment by RangerMauve** [comment]
- Decide on conditions for pricing
 - Free for one site (no videos?)
 - Need disclaimer for when this might change?

**Comment by fauno** [comment]
Looks ok!

**Comment by AnaFukelman** [comment]
FAQs and Pricing are being reviewed by the team
The "cloning instructions" look like this - 
![Image](https://github.com/user-attachments/assets/76ac95de-17e0-48d4-b3c7-1748e69be6ab)
