### ISSUE TITLE
Create fediverse offering pitch deck

### ISSUE THREAD

**Issue by AnaFukelman** [hyphacoop/distributed-press-organizing#203]
We met to share ideas about how to pack the fediverse offering. Had a meeting with Mauve and fauno to discuss it and then Andi and Ania made a summary [here](https://docs.google.com/document/d/1TFOzORfdelQyoLFa5MTSvVmXbWnY115TGCz6KMh-DWQ/edit#heading=h.jxx3oaimbsv): 

I made a first drat of a **pitch deck** based on all of that:

https://docs.google.com/presentation/d/1cSAMzZW5ZwMoRFiCzoXxzhRpxK7bdMTV663CSwiwD-M/edit?usp=sharing

**Comment by RangerMauve** [comment]
This looks great!

**Comment by akhileshthite** [comment]
> We met to share ideas about how to pack the fediverse offering. Had a meeting with Mauve and fauno to discuss it and then Andi and Ania made a summary [here](https://docs.google.com/document/d/1TFOzORfdelQyoLFa5MTSvVmXbWnY115TGCz6KMh-DWQ/edit#heading=h.jxx3oaimbsv):
> 
> I made a first drat of a **pitch deck** based on all of that:
> 
> https://docs.google.com/presentation/d/1cSAMzZW5ZwMoRFiCzoXxzhRpxK7bdMTV663CSwiwD-M/edit?usp=sharing

Yep, looks great!
