### ISSUE TITLE
Accepting URL and/or domain to clone website

### ISSUE THREAD

**Issue by AnaFukelman** [hyphacoop/distributed-press-organizing#207]
In the second step of this flow, we ask for a URL or a domain but then the form input is type="url" with require

https://distributed.press/website-url/index.html?confirm=I+confirm+that+DNS+is+configured

![Image](https://github.com/user-attachments/assets/b4b13ac6-efcd-42cd-9506-53fffa2b20fe)

**Comment by fauno** [comment]
i went with url format so we have browser validation, i can remove the "or domain"

**Comment by AnaFukelman** [comment]
> i went with url format so we have browser validation, i can remove the "or domain"

ok! remove the "or domain" 👌

**Comment by sutty-coop** [comment]
> ok! remove the "or domain" 👌 

done!
