### ISSUE TITLE
Benny's TODOs

### ISSUE THREAD

**Issue by bennlich** [hyphacoop/distributed-press-organizing#29]
📅 **Due date:** ?

### Technical prototyping
all protocols
- [x] make sure links + paths work as built by hugo (relative paths, always to files instead of folders)

brave
- [ ] test ipfs fetch

ipfs
- [x] publish compost prototype page on ipfs
- [x] test ipfs fetch when loading compost over ipns:// on agregore
- [ ] ~~test ipfs fetch when loading compost over ipns:// on opera~~

hypercore
- [x] publish compost prototype page on hypercore
- [x] test hypercore fetch when loading compost over hyper:// on agregore
- [ ] ~~test beaker fetch when loading compost over hyper:// on beaker~~

http
- [x] test http fetch when loading compost over https://
- [x] test web monetization detection

### Design
- [x] design web monetization ux for the support us page (and maybe piece pages?)

### Build
- [x] make a readable hugo directory structure + run it by udit
- [x] implement layouts from made by super **BLOCKED**

**Comment by benhylau** [comment]
@bennlich the sites are back up and all the monetization APIs are working again :D

See: https://github.com/hyphacoop/api.distributed.press#guide for all the links. We also published the production ones, so you can omit the `staging.` for your pages.

**Comment by bennlich** [comment]
Rad! @benhylau Just tested over http, and it looks like I need some CORS headers set on that API reply :) :) :)

**Comment by uditvira** [comment]
Dropping things we discussed today:

## Home page
1. In medium and wide, align the top of the image and the top of the text box
2. Add mushrooms to the bottom, but check with background pattern
3. Have slightly bigger nav bar (reference ben's PR)
4. Change the mobile front page image

## Links
1. Remove all link underlines in footer, keep link underlines only in content 
2. Increase underline spacing under the text 

## Text weight
1. Adjust based on background pattern. Overall weight feels heavy

## Footnotes
Breaks in medium view, might need to adjust break point

## Angelical gifs
1. Make them inline, e.g. on Magma Collective https://magmacollective.org/

## Support us:
1. Change text to  >>
We are building towards a digital commons: publishing our work freely and stewarding tools for anyone to use. If you like what we’re doing, consider supporting us!
2. Change mushroom GIF > two flowers GIF
3. Move the aniGIFs next to the titles

## Hanami Asks
1. Home mushroom in the bottom nav becomes blurred when pops
2. Web monetization mushroom
3. Re-export bottom 4 gifs (Benny's exports are pixelated) https://github.com/hyphacoop/one.compost.digital/tree/master/static/images

## TOC pop up page
1. Try dotted line in nav
2. Remove footer
3. Try background pattern on the TOC page from end to end
