### ISSUE TITLE
Make CI scripts for one.compost.digital

### ISSUE THREAD

**Issue by ASoTNetworks** [hyphacoop/distributed-press-organizing#36]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Feb 13, 2021  
🎯 **Success criteria:** Auto deploy using CI for one.compost.digital. 

## Task Summary

Make CI for publishing one.compost.digital to WWW and Dweb and verify if they are accessible.

## To Do
- [x] Create CI scripts
- [x] Verify WWW
- [x] Hypercore
- [x] IPFS

**Comment by benhylau** [comment]
Let's merge https://github.com/hyphacoop/one.compost.digital/pull/1 and not worry about hypercore since that'll sort once #33 resolves.
