### ISSUE TITLE
COMPOST theme in Sutty: Add a white labeled COMPOST theme to Sutty’s set of managed themes, with appropriate customizations that would be suitable for magazine publishing.

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#44]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

...

## To Do

- [ ] ...

**Comment by sutty-coop** [comment]
[Repository](https://0xacab.org/sutty/jekyll/compost-jekyll-theme/-/issues/1)

**Comment by sutty-coop** [comment]
- We had technical and user experience / design interaction conversations in several meetings with Mai and Ben, about possible scopes of this task. Some definitions are not ready yet, there are potential (useful) overlaps among the creation of the theme and the development of Compost 3rd issue.

- We scheduled a kick-off meeting for this task on November 8th

**Comment by fauno** [comment]
Updates:

* COMPOST theme port is complete and available in the CMS
* COMPOST 03 work is based on this theme
* We're working on adding default content so it looks better and self-explained

**Comment by RangerMauve** [comment]
I think this is done now?
