### ISSUE TITLE
Add Mauve to Distributed Press Digital Ocean team so they can mess with DNS

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#55]
## SSH access to Dev environment on Digital Ocean

| Person | SSH key |
|:--|:--|
| @RangerMauve | `ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxHdTHJS9xDM+JWZyaW7Pf3o0imwVWkwFiLefsHjmMcxOvtInJKNtyIcqgPvUPkP4MGvSrXW0hEvzSEvZsNsMLO86K60HAYbrrcFLGLeuDC8PUMARsqUS5tc0drd31SGdSZdzebcgnv1bg1SSg89Mz2HZb/ApUrOW7IWKxapOaUHgKPldj7gouNXHsFA1o8sktV24l7GHMcqtDSzn2JbEWJDd6ntQ1u/eqUKGo7e9i4mg97k5IdmIPJL+VPtKVqU7f/O7OpDE868u6+/jeerJb7ZKW9QwqnrK+FzZNJACT5MfplCi7zbx7duzPukl96c8hdoT3BNSZM3FyNB6/v8VjIK+5+x2shWkg0hboennDIC824cg2Bfw8YlALYeTt75kfHdfPinJ3eUSIiUsybzal7y7NIhkacUuSIasqGtkqiCt+9ZExqnLgK2Y7KDdL6SpWgEpT41MYqA+onhDiTC7GQbm6RqCKY8n/WnkiUU825nDkeNy3VDaFBi/+1pncOEmSviiPkxbu1v9ClgNF62c3yjTNvbEB0JtoDfMkkrWw+AhMlUFQxd7xyW+2SGmv/2XYHDyitWJzV5cZylpRD14Vlc3UofQ3ffIKR1IjvV4dv7r5lQ0NbPjyV7Yn8NMAmU8Myq4KfYY9/al/vXCQRpBrG7rjNmIJtkuXTaKw1/Xdzw== ranger@mauve.moe` |
| @fauno | `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIOceAWSgtO+0pFhvhYGMlHTbpXIN1LDJK1Hx0qgw9qW` |

Related: https://github.com/hyphacoop/api.distributed.press/issues/10

**Comment by benhylau** [comment]
We are going to do this:

- Production on dedicated host (https://api.distributed.press): get mauve SSH access
- Staging on dedicated host: currently offline, leave it off
- DO Staging Team: create for @RangerMauve 

@YurkoWasHere can you do this?
@RangerMauve send SSH key over? For DO we'll use your hypha email?

**Comment by benhylau** [comment]
## Current DNS setup

`distributed.press` and `compost.digital` are registered with Namecheap:

<img width="267" alt="Screen Shot 2022-09-22 at 5 26 29 PM" src="https://user-images.githubusercontent.com/2261308/191854200-7f45ee0b-763f-401f-91f7-296af0a0e57d.png">

`distributed.press` and `api.distributed.press` is set up with simple A records and email forwards:

<img width="1132" alt="Screen Shot 2022-09-22 at 5 26 54 PM" src="https://user-images.githubusercontent.com/2261308/191854283-ad39c90a-eedf-4688-98bf-65a50175d2e4.png">

<img width="1105" alt="Screen Shot 2022-09-22 at 5 28 53 PM" src="https://user-images.githubusercontent.com/2261308/191854505-a5113720-9126-438e-a945-4f9ae02de2c8.png">

At the moment, `compost.digital` is just root NS'd to Digital Ocean (DO):

<img width="1154" alt="Screen Shot 2022-09-22 at 5 22 56 PM" src="https://user-images.githubusercontent.com/2261308/191853609-732f3068-f84d-40a3-940e-14aaef0d9ba8.png">

Distributed Press (via DO) manages a bunch of domains (there are more I didn't capture):

<img width="706" alt="Screen Shot 2022-09-22 at 5 24 25 PM" src="https://user-images.githubusercontent.com/2261308/191853852-91269f37-cab7-4a83-852c-4c05668f8606.png">

**Comment by RangerMauve** [comment]
I think I'm good to go on this one. 👍

**Comment by benhylau** [comment]
@YurkoWasHere hey how can @RangerMauve VPN in then SSH into the DP instance? Need an internal IP? Can we put a few steps here?

**Comment by YurkoWasHere** [comment]
All access over VPN

All connections have to go through Jump Server
https://handbook.hypha.coop/guides.html#jump-server
(or `ssh sysadmin@ansible1.hypha.prod -p 9154 `)

Distributed Press server is `srv1.distributed-press.prod`

ssh key password for the jump server can be found in bitwarden under `Infra: [Ansible1.hypha.coop](http://ansible1.hypha.coop/) - Production Deploy SSH key` in projects\compost collection

**Comment by fauno** [comment]
here's mine

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIOceAWSgtO+0pFhvhYGMlHTbpXIN1LDJK1Hx0qgw9qW
```

**Comment by ASoTNetworks** [comment]
The login info to the DO server is root@dp.chanterelle.xyz and I have added the keys above.

**Comment by RangerMauve** [comment]
This is done!
