### ISSUE TITLE
Porting Distributed Press site to Sutty

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/distributed-press-organizing#56]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Nov 3, 2022  
🎯 **Success criteria:** ...  

## Task Summary
- Finishing porting 
- 

## To Do
- [ ] Mauve look into current version of Distributed Press server
- [ ] Ping hypha about delegating distributed.press DNS to @sutty-coop

**Comment by sutty-coop** [comment]
The distributed.press website is currently 2/11 under testing.

Test site at https://distributed-press.sutty.nl

Blog will be at distributed.press/blog/

**Comment by jackyzha0** [comment]
Closing as completed
