### ISSUE TITLE
New site `public` field should be optional.

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#82]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

We should allow omitting the `public` field in `/v1/site` in the API and have it use a default value when creating / ignore it in general when updating.

## To Do

- [x] Mark the `public` field in sites as optional
- [x] When updating a site check if the field exists and only change it if it was provided (else merge with whatever was there already)
- [x] Test
- [x] Release

**Comment by sutty-coop** [comment]
can it be `false` by default?
